Repository finos/OpenMAMA, pull requests merged in 2018-05, with the labels that each got.

#353 PLAT 1371
  common/c_cpp/src/c/linux/machine.c
Labels: task

#355 PLAT-1378
  common/c_cpp/src/c/linux/machine.c
Labels: bug

#354 PLAT-1181: Implement MamaFieldCache in JNI
  mama/jni/build.xml
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCache.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheBool.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheChar.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheDateTime.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheEnum.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheField.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheFieldList.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheFloat32.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheFloat64.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheInt16.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheInt32.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheInt64.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheInt8.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCachePrice.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheProperties.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheReadOnlyField.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheString.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheUint16.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheUint32.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheUint64.java
  mama/jni/src/main/java/com/wombat/mama/MamaFieldCacheUint8.java
  mama/jni/src/main/java/com/wombat/mama/examples/MamaListenCached.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/Main.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheBoolTest.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheCharTest.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheDateTimeTest.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheEnumTest.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheFieldListTest.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheFieldTest.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheFloat32Test.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheFloat64Test.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheInt16Test.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheInt32Test.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheInt64Test.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheInt8Test.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCachePriceTest.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCachePropertiesTest.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheStringTest.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheTest.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheUint16Test.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheUint32Test.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheUint64Test.java
  mama/jni/src/test/java/com/wombat/mama/junittests/fieldcache/MamaFieldCacheUint8Test.java
Labels: enhancement

#357 PLAT-1167
  mama/c_cpp/src/c/mama/price.h
  mama/c_cpp/src/c/priceimpl.c
  mama/c_cpp/src/c/priceimpl.h
  mama/c_cpp/src/gunittest/c/mamaprice/pricerangetests.cpp
  mama/c_cpp/src/gunittest/cpp/MamaPriceTest.cpp
  mama/c_cpp/src/gunittest/cpp/MamaPriceTest.h
  mama/dotnet/src/cs/MamaPrice.cs
  mama/jni/src/junittests/MamaPriceDecimalPlaces.java
  mama/jni/src/main/java/com/wombat/mama/MamaPricePrecision.java
Labels: enhancement

#362 Fix timezone double add in mamaDateTime_getAsFormattedStringWithTz(),…
  mama/c_cpp/src/c/datetime.c
Labels: bug
